name: Python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: 2.7
        - python-version: 3.5
          coverage: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pylint pytest mock codecov pytest-cov
          pip install -r requirements.txt

      - name: Lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=15 --max-line-length=200 --show-source --statistics
          pylint --max-line-length=200 --disable=missing-docstring,relative-import,duplicate-code,too-many-branches,too-many-arguments **/*.py

      - name: Test
        run: pytest --cov-config=tests/.coveragerc --cov=. tests

      - name: Upload code coverage
        if: ${{ github.event_name != 'pull_request' && matrix.coverage }}
        run: codecov
